FROM golang:1.23.4-bullseye AS builder

ARG PSQL_CONNECTION_STRING
ENV PSQL_CONNECTION_STRING=${PSQL_CONNECTION_STRING}

ARG CONFIG
ENV CONFIG=${CONFIG} 

WORKDIR /
ENV GOFLAGS=-buildvcs=false
COPY . .
RUN make orchestrator_service

FROM ubuntu:jammy AS app
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=builder /orchestrator_service /orchestrator_service

RUN apt-get update --quiet --yes \
  && apt-get upgrade --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    dnsutils \
    gnupg2 \
    libgmp10 \
    libgomp1 \
    libssl3 \
    libpq-dev \
  && rm -rf /var/lib/apt/lists/*

RUN echo "downloading mina" \
  && echo "deb [trusted=yes] http://packages.o1test.net jammy umt" > /etc/apt/sources.list.d/mina.list \
  && apt-get update --quiet --yes \
  && apt-get install --quiet --yes --allow-downgrades \
    mina-mesa-mut=4.0.0-rc1-mesa-mut-d7513d4 \
    mina-mesa-mut-config=4.0.0-rc1-mesa-mut-d7513d4 \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/sh", "-c", "/orchestrator_service -conn \"$PSQL_CONNECTION_STRING\" -config \"$CONFIG\" -address \":9090\"" ]
