package main

import (
	"strings"
	"testing"

	lib "itn_orchestrator"
	service_inputs "itn_orchestrator/service/inputs"
)

// TestRedactedSetupKeepsTheWebhookURLOutOfTheScript is the regression test for
// a credential leak through an unauthenticated endpoint.
//
// The generated script carries a header comment holding the request body. That
// comment is printed through StoreLogging, so it lands in
// ExperimentState.Logs, and GET /api/v0/experiment/status serves Logs to any
// caller. For Slack, Discord and Teams the webhook URL is the credential, so
// it must not be in that comment. The private-key paths go the same way.
func TestRedactedSetupKeepsTheWebhookURLOutOfTheScript(t *testing.T) {
	const secret = "https://hooks.slack.com/services/T000/B000/SUPERSECRETTOKEN"
	name := "leak-probe-1"
	webhook := secret
	receiver := lib.DefaultGenParams().PaymentReceiver

	setup := &service_inputs.GeneratorInputData{
		ExperimentName: &name,
		WebhookURL:     &webhook,
		Privkeys:       []string{"/run/secrets/privkeys/key-1"},
	}
	setup.PaymentReceiver = &receiver

	var p lib.GenParams
	setup.ApplyWithDefaults(&p)

	var script strings.Builder
	if _, err := lib.EncodeToWriter(&p, &script, setup); err != nil {
		t.Fatalf("EncodeToWriter: %v", err)
	}

	// The whole script is checked for the webhook URL, and the header comment
	// for the key paths. The paths also appear in the fund and load-keys
	// commands, where they are what the run needs; the header comment is the
	// only place they are echoed back for no reason.
	if strings.Contains(script.String(), secret) {
		t.Fatal("the generated script carries the webhook URL; GET /status would hand it to any caller")
	}
	var header string
	for _, line := range strings.Split(script.String(), "\n") {
		if strings.Contains(line, "Generated by orchestrator service") {
			header = line
			break
		}
	}
	if header == "" {
		t.Fatal("no setup header comment in the generated script; this test no longer covers the leak")
	}
	if strings.Contains(header, "/run/secrets/privkeys/key-1") {
		t.Fatalf("the setup header comment carries the private-key paths: %s", header)
	}

	// The redaction must not mutate the caller's struct: the delivery path
	// reads the same pointer afterwards.
	if setup.WebhookURL == nil || *setup.WebhookURL != secret {
		t.Fatal("Redacted() modified the original setup; the notifier would then have no destination")
	}
}
