name: Uptime Backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Docker image
        run: docker build -t uptime-backend:latest .
        working-directory: ./uptime-backend